### ISSUE TITLE
Gazebo doesn't shows up

### ISSUE THREAD

**Issue by JorgelHenri** [ctu-mrs/mrs_singularity#2]
When I start any simulation, the MRS looks fine and I could notice that uav takes off, but the gazebo windows do not appear
![Screenshot from 2022-04-29 17-12-57](https://user-images.githubusercontent.com/63995982/166062934-9c376e69-93e4-405a-ae8d-afa3b36b09fe.png)
![Screenshot from 2022-04-29 17-13-07](https://user-images.githubusercontent.com/63995982/166062948-cdc52ec8-a349-4649-a324-191362e7c53d.png)
.

**Comment by klaxalk** [comment]
Hey, do you have Nvidia graphics?

**Comment by JorgelHenri** [comment]
Yes, GTX 1050ti and 920m (laptop).

**Comment by yhdurkaya** [comment]
I am going through the same problem at the moment. Did you guys figure out a solution?

**Comment by klaxalk** [comment]
Hey, could you please switch `debug` to true in the `wrapper.sh`? That should make it print the final singularity command. Please post it here.

Moreover, what happens if you run just the command
```bash
gazebo
```
in the singularity terminal?

And finally, could you please post the terminal output from the `one_drone_gps` tmux session, particularly, from the Gazebo tab? I am interested in seeing what Gazebo prints when/if it crashes.

**Comment by yhdurkaya** [comment]
When I I switch debug to true, wrapper.sh prints this into the terminal.

`singularity run --nv --home /tmp/singularity/home:/home/vision --mount type=bind,source=/home/vision/mrs_singularity/user_ros_workspace,destination=/home/vision/user_ros_workspace --mount type=bind,source=/home/vision/mrs_singularity/mount,destination=/opt/mrs/host --bind /tmp/singularity/tmp:/tmp /home/vision/mrs_singularity/images/mrs_uav_system.sif`

I switch debug to false and run the container. Inside the container, when I try to run gazebo, it just prints "No protocol specified" to the singularity terminal twice.

As the last one, this is the output of gazebo part of the terminal.

![ss](https://user-images.githubusercontent.com/47098320/168597499-91a028ae-68d0-435e-8c38-46ae8fe7d557.png)

**Comment by klaxalk** [comment]
Hmm, could you please verify that other GUI applications do NOT run as well? E.g., by calling
```bash
 roslaunch rqt_bag rqt_bag.launch
```

If it confirms that the problem affects all GUI programs, we need to investigate what is different with your machine. Could you please check what is your current $DISPLAY variable on your host machine?
```bash
echo $DISPLAY
```

I am explicitly setting DISPLAY=:0 for the container, so that my be over-specifying it on my side.

**Comment by yhdurkaya** [comment]
![SS2](https://user-images.githubusercontent.com/47098320/168993002-e97422ca-be80-4952-ba54-ce7708f384d9.png)
When I run `roslaunch rqt_bag rqt_bag.launch`, the above error occurs. But I realized that ` echo $DISPLAY` prints 1 on my host and this error says that "Could not connect to display:0

So I changed display setting `export SINGULARITYENV_DISPLAY=:0` into one and rqt works as expect, no problem on GUI. After that, I tried to run 
`cd /opt/mrs/git/simulation/example_tmux_scripts/one_drone_gps`
`./start.sh`
and Gazebo works as expected and I can see the Gazebo and RViz perfectly. 

I am writing this for future researchers that might encounter with same issue.

Thanks for all your help @klaxalk, I really appreciate it.

Since I didn't create this issue, I can't close it but I think could be the same problem @JorgelHenri faced.

**Comment by yhdurkaya** [comment]
One last question totally unrelated to this. Is there a way to clearly shut down the process. When I use CTRL+C, it stays as a zombie process and I have to restart my computer for a clean start. Otherwise I can't run the simulation for a second time. I couldn't see an exit way that is why I am asking.

**Comment by klaxalk** [comment]
Thanks, guys @JorgelHenri, @yhdurkaya, I will update the wrapper script to automatically pass whatever $DISPLAY you already have on your host machine.
