### ISSUE TITLE
Instructions on terminating the simulator

### ISSUE THREAD

**Issue by lassepe** [ctu-mrs/mrs_singularity#6]
This may be trivial but it was/is not clear to me from the instructions how to gracefully stop the simulator and all the related nodes. For example, when I naively kill the simulator tmux I just got detached and ended up with a bunch of dangling services (such as the flight PX4 flight controller). Are there some instructions somewhere what is the correct way to stop the simulation and all related service? If so, it may be a good idea to link to those instruction in the README here right after the instruction that explain how to start the simulator.

**Comment by yhdurkaya** [comment]
If I remember correctly, CTRL+A+K terminates the entire simulator. This way, there is no dangling services as you mentioned.

**Comment by petrapa6** [comment]
Since commit [#4004758](https://github.com/ctu-mrs/mrs_simulation/commit/4004758531cb3bf3253ff3e91a57245670ecb8c5), all running processes of `mavros_node mavros px4 gazebo_ros gazebo` will be killed automatically while launching `mrs_simulation simulation.launch`. Although this should prevent issues where the simulation is not launching due to ghost processes living in the background, I agree we should also document the correct termination process.
